version: "3.8"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3200:5173"
    networks:
      - app-network
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

networks:
  app-network:
    driver: bridge
