services:
  backend:
    build:
      context: ./server
    ports:
      - "5001:5001"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
