services:
  backend:
    build: ./backend
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    env_file:
      - ./backend/.env
    restart: unless-stopped
    
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge