# version: "3.8"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000" # Maps port 3000 of the container to port 3000 of your machine
#     volumes:
#       - .:/app # Mounts the current directory to the container for development
#       - /app/node_modules # Ensures node_modules inside the container is isolated
#     environment:
#       - NODE_ENV=development

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev # Assuming you have a dev script in package.json
    environment:
      - NODE_ENV=development
