services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - default
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge
